project:
  type: book
  output-dir: docs

book:
  title: "Methodology for the Fiscal Futures Annual Report"
  subtitle: "Part of IGPA's Fiscal Futures Project"
  author: "Alea Wilbur-Mujtaba"
  date: last-modified
  search: true
  repo-url: https://github.com/AleaWM/Fiscal-Futures/
  chapters:
    - index.qmd
    - part: "Reports"
      chapters:
      - Everything.qmd 
      - Everything_changepensions.qmd
 #    - FiscalGap.qmd    
    - part: "Illinois State Budget Data"
      chapters: 
        - OwnSourceRev.qmd
        - FederalRevenue.qmd
        - LocalTransfers.qmd
        - Medicaid.qmd
        - Debt.qmd
        - Pensions.qmd
        - Healthcare.qmd
        - TaxRefunds.qmd
        - K12_Education.qmd
        - FedMoneyReceived.qmd
    - part: "Methodology"
      chapters: 
        - FundsIncluded.qmd
        - code-cleaning.qmd
        - past-mistakes.qmd

  navbar: 
    # right: 
    #   - icon: github
    #     href: https://github.com/AleaWM/Fiscal-Futures.git
    left:
      - text: "About"
        file: index.qmd
      - text: "Methodology"
        menu:
          - FundsIncluded.qmd
          - code-cleaning.qmd
          - Everything.qmd
      - text: "Data"
        href: https://github.com/AleaWM/Fiscal-Futures/tree/main/data
#      - text: "Reports"
#        file: FiscalGap.qmd
 #     - text: "COVID-related Federal Revenue"
 #       file: FedMoneyReceived.qmd


        

format:
  html:
    theme: zephyr
    toc: true
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged
 