book:
# Book specific overrides for personal build
  title: "Personal Website for the Methodology for the Fiscal Futures Project"
  subtitle: "Original Code for IGPA's Fiscal Futures Project"
  author: "Alea Wilbur-Mujtaba"
  date: last-modified
  search: true
  repo-url: https://github.com/AleaWM/Fiscal-Futures/
 
  chapters:
    - index.qmd
    - part: "Reports"
      chapters:
        - Everything.qmd
        - Everything_changepensions.qmd
    - part: "Illinois State Budget Data"
      chapters:
        - OwnSourceRev.qmd
        - FederalRevenue.qmd
        - LocalTransfers.qmd
        - Medicaid.qmd
        - Debt.qmd
        - Pensions.qmd
        - Healthcare.qmd
        - TaxRefunds.qmd
        - K12_Education.qmd
        - FedMoneyReceived.qmd
    - part: "Methodology"
      chapters:
        - FundsIncluded.qmd
        - code-cleaning.qmd
        - past-mistakes.qmd
 
 
  navbar: 
    left:
      - text: "About"
        file: index.qmd
      - text: "Methodology"
        menu:
          - FundsIncluded.qmd
          - code-cleaning.qmd
          - Everything_changepensions.qmd
      - text: "Data"
        href: https://github.com/AleaWM/Fiscal-Futures/tree/main/data
  # # Profile-specific metadata for the PERSONAL build
  # # Structured authors (shows up in page header + HTML metadata)
  # author:
  #   - name: "Alea Wilbur-Mujtaba"
  #     email: "awilbu2@uic.edu"
  #     roles: [author]
  #     affiliations: [igpa]
  # 
  #   # Define affiliations once and reference by id in authors
  #   affiliations:
  #     - id: igpa
  #       name: "Institute of Government & Public Affairs (IGPA)"
  #       url: "https://igpa.uillinois.edu"
  # 



org_name: "Alea Wilbur / Fiscal Futures (Personal Edition)"
contact_url: "mailto:awilbu2@uic.edu"
# Markdown snippets that differ by profile (rendered in index.qmd)
author_note: "*Note from **Alea Wilbur-Mujtaba**: This edition reflects my personal working notes and documentation. It may include in-progress analyses and commentary intended for rapid iteration.*"
  
profile_intro: "This **personal** build prioritizes fast iteration and exploratory content. Links to IGPA-managed resources may point back to this repo."
   

