project:
  type: book

book:
  title: "Fiscal-Future-Topics"
  author: "Alea Wilbur-Mujtaba"
  date: "12/21/2022"
  chapters:
    - index.qmd
    - Medicaid.qmd
    - Debt.qmd
    - Pensions.qmd
    - Healthcare.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

