project:
  type: book
  output-dir: docs

book:
  title: "Fiscal Futures Project"
  author: "Alea Wilbur-Mujtaba"
  date: last-modified
  navbar: 
    right: 
      - icon: github
        href: https://github.com/AleaWM/Fiscal-Futures
        aria-label: GitHub
  site-url: https://aleawm.github.io/Fiscal-Futures/
  reader-mode: true
  chapters:
    - index.qmd
    - code-cleaning.qmd
    - FedMoneyReceived.qmd
    - LocalTransfers.qmd
    - Debt.qmd
    - Pensions.qmd
    - Healthcare.qmd
    - FederalRevenue.qmd
    - Medicaid.qmd
    - Everything.qmd

#execute: 
#  freeze: auto

format:
  html:
    code-fold: true
    code-tools: true
    code-overflow: wrap
    df-print: paged
    theme: 
      light: lightly
      dark: darkly

#bibliography: references.bib



editor: visual

