project:
  type: book
  output-dir: docs

book:
  title: "Fiscal Futures"
  author: "Alea Wilbur-Mujtaba"
  date: last-modified
  chapters:
    - index.qmd
    - Debt.qmd
    - Pensions.qmd
    - Healthcare.qmd
    - FederalRevenue.qmd
    - Medicaid.qmd
    - FiscalGap.qmd
    - references.qmd
    
format:
  html:
    code-fold: true
    df-print: paged
    theme: cosmo


#bibliography: references.bib



editor: visual

