project:
  type: book
  output-dir: _book

book:
  title: "Fiscal Futures"
  author: "Alea Wilbur-Mujtaba"
  date: last-modified
  chapters:
    - index.qmd
    - Medicaid.qmd
    - Debt.qmd
    - Pensions.qmd
    - Healthcare.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

