project:
  type: book
  output-dir: docs

book:
  title: "Fiscal Futures Project"
  author: "Alea Wilbur-Mujtaba"
  date: last-modified
  chapters:
    - index.qmd
    - FundsIncluded.qmd
    - code-cleaning.qmd
    - FedMoneyReceived.qmd
    - LocalTransfers.qmd
    - Debt.qmd
    - Pensions.qmd
    - Healthcare.qmd
    - FederalRevenue.qmd
    - Medicaid.qmd
#    - FiscalGap.qmd
    - Everything.qmd 
  navbar: 
    right: 
      - icon: github
        href: https://github.com/AleaWM/Fiscal-Futures
    left:
      - text: "About"
        file: index.qmd
      - text: "Methodology"
        menu:
          - FundsIncluded.qmd
          - code-cleaning.qmd
          - FedMoneyReceived.qmd
          - LocalTransfers.qmd
          - Debt.qmd
          - Pensions.qmd
          - Healthcare.qmd
          - FederalRevenue.qmd
          - Medicaid.qmd
          - Everything.qmd
 #     - text: "The FY22 Fiscal Gap"
 #       file: FiscalGap.qmd
 #     - text: "COVID-related Federal Revenue"
 #       file: FedMoneyReceived.qmd

          

site-url: https://aleawm.github.io/Fiscal-Futures/
#  repo-actions: [edit]
#  downloads: [pdf, epub]
#  sharing: [twitter, facebook]
   # sidebar:
      #title: "On this page"


#execute: 
#  freeze: auto

format:
  html:
    code-fold: true
    code-tools: true
    code-overflow: wrap
    df-print: paged
    theme: 
      light: lightly
      dark: darkly
    fig-cap-location: top
    tbl-cap-location: top
    
  # pdf:
  #   documentclass: scrreport
  #   include-in-header: 
  #     text: |
  #       \usepackage{makeidx}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex
  #   
bibliography: references.bib
#reference-location: margin
#citation-location: margin



editor: visual

