project:
  type: book
  output-dir: docs


book:
  search: true
  repo-url: https://github.com/igpa-uillinois/Fiscal-Futures/
  chapters:
    - index.qmd
    - part: "Reports"
      chapters:
        - fy25_revenue_report.qmd
        - Everything.qmd
        - Everything_changepensions.qmd
    - part: "Illinois State Budget Data"
      chapters:
        - OwnSourceRev.qmd
        - FederalRevenue.qmd
        - LocalTransfers.qmd
        - Medicaid.qmd
        - Debt.qmd
        - Pensions.qmd
        - Healthcare.qmd
        - TaxRefunds.qmd
        - K12_Education.qmd
        - FedMoneyReceived.qmd
    - part: "Methodology"
      chapters:
        - FundsIncluded.qmd
        - code-cleaning.qmd
        - past-mistakes.qmd
 
 
  navbar: 
    left:
      - text: "About"
        file: index.qmd
      - text: "Methodology"
        menu:
          - FundsIncluded.qmd
          - code-cleaning.qmd
          - Everything.qmd
      - text: "Data"
        href: https://github.com/igpa-uillinois/Fiscal-Futures/tree/main/data
      - text: "Recent Reports"
        file: fy25_revenue_report.qmd
      - text: "Additional Topics"
        menu:
          - OwnSourceRev.qmd
          - FederalRevenue.qmd
          - LocalTransfers.qmd
          - Medicaid.qmd
          - Debt.qmd
          - Pensions.qmd
          - Healthcare.qmd
          - TaxRefunds.qmd
          - K12_Education.qmd
          - FedMoneyReceived.qmd
      
format:
  html:
    theme: zephyr
    #toc: true
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged


