project:
  type: book
  output-dir: docs



book:
  search: true
  repo-url: https://github.com/igpa-uillinois/Fiscal-Futures/
  author:
    - name: "IGPA Research Team"
      roles: [author]
      affiliations: [igpa]
    - name: "Alea Wilbur-Mujtaba"
      roles: [author][contributor][maintainer]
      affiliations: [igpa]
  chapters:
    - index.qmd
    - part: "Reports"
      chapters:
        - Everything.qmd
        - Everything_changepensions.qmd
    - part: "Illinois State Budget Data"
      chapters:
        - OwnSourceRev.qmd
        - FederalRevenue.qmd
        - LocalTransfers.qmd
        - Medicaid.qmd
        - Debt.qmd
        - Pensions.qmd
        - Healthcare.qmd
        - TaxRefunds.qmd
        - K12_Education.qmd
        - FedMoneyReceived.qmd
    - part: "Methodology"
      chapters:
        - FundsIncluded.qmd
        - code-cleaning.qmd
        - past-mistakes.qmd
        
# Define affiliations once and reference by id in authors
affiliations:
  - id: igpa
        name: "Institute of Government & Public Affairs (IGPA)"
        url: "https://igpa.uillinois.edu"
      
          
format:
  html:
    theme: zephyr
    toc: true
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged

