# Background Information {#sec-background-info .unnumbered}

---
format:
  html:
    code-fold: false
    code-tools: true
    code-overflow: wrap
---

While the main purpose of this site is documenting methodology used in the Fiscal Futures Annual Report, it **also contains useful information on Illinois budget variables used by the Illinois Office of the Comptroller (IOC) that may be valuable to other researchers**. Frequently discussed topics (e.g. Pensions, Debt, Federal Revenue Sources, Medicaid, etc.) each have their own section on this site dedicated to looking at the many relevant variables for that topic, even if the budget variables are not directly included while calculating the Fiscal Gap for the Fiscal Futures Annual Report.

> This is a novel dataset containing all revenue items and all expenditure items from fiscal years (FY) 1998 to 2023 received through yearly FOIA requests to the Illinois Comptroller. The data can be downloaded in this page's data folder. To the authors' knowledge, the revenue and expenditure data used in the analysis does not exist elsewhere and cannot be downloaded from the Comptroller's website or the Illinois Data Portal in this format.

This website was originally created by Alea Wilbur-Mujtaba as an internal document for Fiscal Futures researchers to increase reproducibility and update the methodology documentation used for the Fiscal Futures Annual Report. Until August 2022, The FF Annual Report was calculated using Stata code and documentation that had been passed on for years and modified in a piece-meal fashion. AWM translated the Stata files into a very long Rmarkdown file before transitioning to a Github Page with downloadable public data. She also created the method for comparing funds/agencies/revenue sources in current and past fiscal years, identified the important data values and code relevant for various fiscal topics, and coded all files associated with creating this website. The methodology for selecting funds to include in the Fiscal Gap calculation and tracking them over time was created by David Merriman and Richard Dye and updated with the help of many PhD researchers since 2008.

*Note from Alea Wilbur-Mujtaba: This document is a good faith effort to increase reproducibility and transparency for both the Fiscal Futures Annual Report and Illinois budget data as a whole. I recognized that the time and effort spent on identifying variables and graphing fiscal topics could be valuable to other researchers and took the initiative to create this page and repository from the documents I inherited as an IGPA Research Assistant. This endeavor has had a sharp learning curve and I could easily have made mistakes along the way. This is a working document and small edits are made to the site frequently. I intend to document major changes with new repository releases.*

Read the FY23 Fiscal Futures Report here: [Finding the Balance: State Fiscal Sustainability and Local Government Challenges](https://igpa.uillinois.edu/reports/finding-the-balance-state-fiscal-sustainability-and-local-government-fiscal-challenges)

-   Alea Wilbur-Mujtaba, Francis Choi, Rick Funderburg, Xiaoyan Hu, Paula R. Worthington, Yonghong Wu, Chen Xie, & David Merriman. "Finding the Balance: State Fiscal Sustainability and Local Government Challenges." (2024). Institute of Government and Public Affairs. <https://igpa.uillinois.edu/reports/finding-the-balance-state-fiscal-sustainability-and-local-government-fiscal-challenges>.

You can read the FY22 Fiscal Futures Annual Report here: [Recovering from a (COVID) Spending Fever](https://igpa.uillinois.edu/wp-content/uploads/2023/03/IGPA_FiscalFuturesCOVID_FeverD.pdf)

-   Alea Wilbur-Mujtaba, Francis Choi, and David Merriman. (2023). "Recovering from a COVID (Spending) Fever." Institute of Government and Public Affairs. <https://igpa.uillinois.edu/wp-content/uploads/2023/03/IGPA_FiscalFuturesCOVID_FeverD.pdf>.

To learn more about the history of the Fiscal Futures Project and read past reports, please visit [The Fiscal Futures webpage.](https://igpa.uillinois.edu/fiscal-futures-project/) The Fiscal Future Project is one of many research projects within the University of Illinois' [Institute of Government and Public Affairs (IGPA)](https://igpa.uillinois.edu/).

## Github Data Notes and Organization

The authors and IGPA believe that these novel datasets will be valuable to other researchers interested in Illinois' finances.

-   Original files as they were received from FOIA requests is in the `data/DATA_RAW` folder. The version of the files used in the analysis and to create this website are in the `data/DATA_DTA` folder. The files within these folders are **before** cleaning or recoding the data. Most of the files for individual years are saved as .dta files due to using Stata before FY21.

-   `allexp_fy23_recoded.csv` and `allrev_fy23_recoded` are probably the best for any researchers trying to use this data in their own projects.

    -   Cleanest version of data before aggregating totals or dropping observations not included in the Fiscal Futures fiscal gap calculation. All years in one file. Funds and agencies should have numbers and consistent labels. Includes the "Group" variable used in the FF Annual Report used for calculating expenditures by function. *To do: Add group names to go with group number code. Done after pivoting and merging in normal Fiscal Gap calculation code.*
    -   Created in February 2023. Still checking accuracy. AWM made this version of the data specifically for other researchers. The normal work flow for the Annual Report involves dropping observations gradually while cleaning and coding the data. Significant changes to the code used for the Annual Report were made to create a new dataset that attempts to keep all Illinois budget observations that have been consistently coded over time with the additional descriptive variables used by Fiscal Futures researchers. Again, I cannot guarantee the accuracy of this file but the original data and code for cleaning the data is available to get you started.

`exp_temp` and `rev_temp`

-   Used in fiscal gap calculation. Data is cleaned and coded up to the point right before aggregating category totals. Drops observations we do not keep in fiscal gap calculation.

A summary file containing aggregated yearly expenditure and revenue values for categories used in the Fiscal Futures model can be found in the `summary_file_FY2023.xlsx` excel file. This excel file also contains additional tabs for all CAGR values calculated as well as the yearly change between the most recent fiscal year and the previous fiscal year. All tables included in the Annual Report are in the summary file.

*The Annual Report is part of Fiscal Futures project associated with the University of Illinois System Institute of Government and Policy Affairs (IGPA). Creating the R code, Github folder, and website for methodology was done by Alea Wilbur-Mujtaba. Any errors with code or findings are the fault of the author, not the research institute. Data is originally from annual FOIA requests to the Illinois Office of the Comptroller.*
