{
  "hash": "535177350b5a0dac09e9d8494bf4c1e3",
  "result": {
    "markdown": "# Background Info {.unnumbered}\n\n> This document is UNFINISHED. Every section is a work in progress and will continue to be updated. - AWM 1/2/2023\n\nThis is a living document in which we aim to describe things as clearly as possible in the time we have, share it with others, and improve as we come back to it. If we wait till we have time to write flawless docs, it'll never happen.\n\nCode and information on the analysis of Illinois' expenditures and revenues. The Fiscal Future Project is associated with the Institute of Government and Policy Affairs but publicly sharing the code and creating a website was done by Alea Wilbur-Mujtaba. Any errors with code or findings are the fault of the author, not the research institute. Data originally from annual FOIA requests to the Illinois Office of the Comptroller.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(haven)\nlibrary(formatR)\nlibrary(lubridate)\nlibrary(smooth)\nlibrary(forecast)\nlibrary(scales)\nlibrary(kableExtra)\nlibrary(ggplot2)\nlibrary(readxl)\nlibrary(tidyverse)\nlibrary(data.table)\nlibrary(quantmod)\nlibrary(geofacet)\nlibrary(janitor)\n\n\nknitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = TRUE)\n```\n:::\n\n\n-   Do the FOIA request. In a week or so, they send the expenditure and revenue data as excel files.\n-   Checks whether there are any new agencies, re-used funds etc. Create a list of funds, agencies, fund names, etc. for the new year and compare it to the immediate prior year to identify new funds.\n-   Update the funds_ab_in file which shows the use of funds. Use criteria to determine if the new funds should be in or out of the all-funds frame.\n-   Change the variable names to be consistent with other files such as AGENCYNAME \\--\\> agency_name\n-   Once variable names are shared over all years of data, combine past years with newest year. All revenue files are in a \\`revenue\\` folder that I reference when I set the working directory. When adding new fiscal years, put the the newest year of data for revenue and expenditures in their respective folders.\n\nNormally, when your receive the new fiscal year files from the Comptrollers office, you will need to change the variable names so that they are consistent with past years. This is an example of reading in the new file and changing the variable names. They seem to change almost every year in the file received from the FOIA so if the code breaks here, check to make sure that the columns you are trying to rename exist and are spelled correctly! Once variables are the same, you will want to save the file as a csv file in its Revenue/Expenditure file and bind all past years and the current year together in one dataframe.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-2_8b6365c46b5b8703403eedbe472b69e7'}\n\n```{.r .cell-code}\n#Example code below: Read in excel file and rename columns so that it plays well with the other years' files.\n\nrevenue_fy22 <- read_xlsx(\"Fis_Fut_Rev_2022_Final.xlsx\") %>% \n\n  rename(fy = 'FY',\n\n         fund = 'FUND',\n\n         fund_name = 'FUND NAME',\n\n         agency = 'AGENCY',\n\n         agency_name = 'AGENCY NAME',\n\n         source = 'REVENUE SOURCE',\n\n         source_name = 'REV SRC NAME',\n\n         receipts = 'AMOUNT'\n\n  ) \n\nexp_fy22 <- read_xlsx(\"Fis_Fut_Exp_2022_Final.xlsx\") %>% \n\n  rename(fy = 'FY',\n\n         fund = 'FUND',\n\n         fund_name = 'FUND NAME',\n\n         agency = 'AGENCY',\n\n         agency_name = 'AGENCY NAME',\n\n         appr_org = 'ORGANIZATION',\n\n         org_name = 'ORGANIZATION NAME',\n\n         obj_seq_type = 'APPROPRIATION',\n\n         wh_approp_name = 'APPROPRIATION NAME',\n\n        # exp_net_xfer = 'NET OF TRANS AMOUNT',\n\n         expenditure = 'EXPENDED'\n\n  ) \n\n# %>%\n\n#   # these come from ioc_source file after merging\n\n#   mutate(data_source = \"exp IOC Aug 2022\",\n\n#          object = ,\n\n#          seq = ,\n\n#          type = ,\n\n#          fund_cat = FIND_COLUMN, #create fund_cat column\n\n#          fund_cat_name = FIND_NAME) # create fund_cat_name column\n```\n:::\n\n\nThe code chunk below takes the .dta files for all fiscal years before FY 2022 and binds them together. Variable names were manually changed by past researchers so that they were consistent across years.\n\nFor FY 2023 and after, .dta files can be avoided entirely and .csv or excel files will be used. All files before this year had been saved and passed on as .dta files for Stata code before the transition to R in Fall 2022. For years after fy22: add line of code to bind csv files after binding the dta files together. Variable names must identical to merge files together.\n\n\n\n\n\nCode below reads in the csv files created in chunks above (allrevfiles.csv and allrexpfiles.csv). These files contain all years of data combined into one file BEFORE any recoding is done. Do not use this file for summing categories because it is just an inbetween step before recoding revenue and expenditure categories.\n\n\n::: {.cell hash='index_cache/html/readCSVs_66fd6cfc4aab8143eb1f0309aec2cbac'}\n\n```{.r .cell-code}\n# combined in past chunks called create-rev-csv and create-exp-csv\n\nallrevfiles22 <- read_csv(\"allrevfiles22.csv\") #combined but not recoded\n\nallexpfiles22 <- read_csv(\"allexpfiles22.csv\") #combined but not recoded\n```\n:::\n\n\n## Inspecting new FY22 data files\n\nData files for closed years have been obtained from IOC. The numbers of funds, agencies, organizations, and revenue sources below were found by using pivot tables in the codebook files in the FY2022 Box folder. This could also be done using R and grouping new files by fund, agency, source number, source names, etc..\n\nRevenue File:\n\n-   684 Fund Numbers\n-   80 Agencies\n-   1184 Revenue source numbers\n-   1156 revenue source names\n\nExpenditure File:\n\n-   708 Fund Numbers\n-   107 Agencies\n-   98 Organization Numbers\n-   313 Organization names\n\n### Finding new agencies and funds\n\nGeneral steps:\n\n1\\. Identify new and reused funds for newest fiscal year.\n\n2\\. Recode funds to take into account different fund numbers/names over the years. See \\[Recoding New and Reused Funds\\] for code chunk that does this.\n\n3\\. Update fund_ab_in_2022.xlsx with any changes from previous fiscal year.\n\n**New Agencies, Funds, and Organizations from Expenditure files:**\n\n-   Using the code below, I found 2 agencies, multiple funds, and a couple organizations that had not been specifically mentioned in the funds_ab_in file - AWM, FY2022.\n\n-   Note: One new org name and org number combo has an expenditure of \\$600 million for pensions payment. Investigate later.\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-3_5814667f6e3d24e1ac6c2ad1644136d3'}\n\n```{.r .cell-code}\nallrevfiles22 <- read_csv(\"allrevfiles22.csv\") #combined but not recoded\n\nallexpfiles22 <- read_csv(\"allexpfiles22.csv\") #combined but not recoded\n\n\n#### From Expenditure Data #####\n\n# agencies referenced in any year before 2020:\n\nagencies_past <- allexpfiles22 %>% filter(fy < 2022) %>% mutate(agency == as.character(agency)) %>% group_by(agency, agency_name) %>% unique() %>% summarize(expenditure = sum(expenditure, na.rm = TRUE)) %>% drop_na() %>% arrange(agency)\n\n# agencies_past # 146 agencies ever\n\n# agencies in 2022 data:\n\nagencies22 <- allexpfiles22  %>% filter(fy == 2022) %>% mutate(agency == as.character(agency)) %>% group_by(agency, agency_name) %>% summarize(expenditure = sum(expenditure, na.rm = TRUE))\n\n# agencies22 # 107 agencies this year\n\n# 280 and 533 are new agency codes: \n\nanti_join(agencies22, agencies_past, by = c(\"agency\", \"agency_name\")) %>% arrange(agency)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 x 3\n# Groups:   agency [2]\n  agency agency_name                expenditure\n   <dbl> <chr>                            <dbl>\n1    280 COURTS COMMISSION               37747.\n2    533 COMM ON EQUITY & INCLUSION    1405788.\n```\n:::\n\n```{.r .cell-code}\nfunds_past <- allexpfiles22  %>% filter(fy < 2022) %>% mutate(fund == as.character(fund)) %>% group_by(fund, fund_name) %>% summarize(count = n(), Expenditure = sum(expenditure, na.rm = TRUE))  %>% drop_na()\n\nfunds22 <- allexpfiles22  %>% filter(fy == 2022) %>% mutate(fund == as.character(fund)) %>% group_by(fund, fund_name) %>%  summarize(count = n(), Expenditure = sum(expenditure, na.rm = TRUE)) %>% unique()\n\n# 15 funds were in FY22 data that were not in past data:\n\nanti_join(funds22, funds_past, by = c(\"fund\", \"fund_name\")) %>% arrange(fund)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 15 x 4\n# Groups:   fund [15]\n   fund  fund_name                      count Expenditure\n   <chr> <chr>                          <int>       <dbl>\n 1 0110  DEV. DISABILITIES AWARENESS        1          0 \n 2 0319  PENSION STABILIZATION             10  300000000 \n 3 0351  FREEDOM SCHOOLS                    1     335306 \n 4 0367  CAP FACILITY TEC MODERNIZATION     2    1000000 \n 5 0392  EQUAL PAY REGISTRATION             1          0 \n 6 0393  SICKLE CELL CHRONIC DISEASE        1          0 \n 7 0422  ELECTRIC VEHICLE REBATE            3     225069.\n 8 0427  ENERGY TRANSITION ASSISTANCE       8    6046483.\n 9 0461  PARITY ADVANCEMENT                 1          0 \n10 0544  DOIT SPECIAL PROJECTS              3    9998632.\n11 0628  ESSENTIAL GOVT SERV SUPPORT        1  736120867.\n12 0634  STATE TREASURER'S CAPITAL          1     250000 \n13 0656  HORSE RACING PURSE EQUITY          1    5908048.\n14 0672  CONSUMER INTERVENOR COMP.          1       2665 \n15 0976  FAIRGROUNDS IMPROVMNT & RACING     1      10000 \n```\n:::\n\n```{.r .cell-code}\n# orgs_pastin the past =  916 org groups ever\n\norgs_past <- allexpfiles22  %>% filter(fy < 2022) %>% mutate(appr_org == as.character(appr_org)) %>% group_by(appr_org, org_name) %>% unique() %>% summarize(Expenditure = sum(expenditure, na.rm = TRUE)) %>% drop_na()\n\n# orgs_past # 916 org groups ever\n\norgs22 <- allexpfiles22  %>% filter(fy == 2022) %>% mutate(appr_org = as.character(appr_org)) %>% group_by(appr_org, org_name) %>% summarize(Expenditure = sum(expenditure, na.rm = TRUE))\n\n# orgs22 # 396 org groups this year\n\n# 4 org number and org name combos are new for FY2022:\n\nanti_join(orgs22, orgs_past, by = c(\"appr_org\", \"org_name\")) %>% arrange(appr_org)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 x 3\n# Groups:   appr_org [4]\n  appr_org org_name                      Expenditure\n  <chr>    <chr>                               <dbl>\n1 05       PAROLE                          53426135.\n2 06       RE-ENTRY SERVICES               18338411.\n3 25       RETIREMENT SYSTEM PMT ADMIN    600000000 \n4 34       IL CRIMINAL JUSTICE INFO AUTH      55659.\n```\n:::\n:::\n\n\n**New Revenue Funds, Sources, and New Agencies:**\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-4_71c4cd7a44456eb48582480e79f6fa61'}\n\n```{.r .cell-code}\n#### From Revenue Data ####\n\n# agencies_past # 108 agencies ever\n\nagencies_past <- allrevfiles22  %>% filter(fy < 2022) %>% mutate(agency == as.character(agency)) %>% group_by(agency, agency_name) %>% unique() %>% summarize(Receipts = sum(receipts, na.rm = TRUE)) %>% drop_na()\n\n# agencies22 # 80 agencies this year\n\nagencies22 <- allrevfiles22  %>% filter(fy == 2022) %>% mutate(agency == as.character(agency)) %>% group_by(agency, agency_name) %>% summarize(Receipts = sum(receipts, na.rm = TRUE))\n\n# 0 new agencies in revenue data this year\n\nanti_join(agencies22, agencies_past, by = c(\"agency\", \"agency_name\")) %>% arrange(agency)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 0 x 3\n# Groups:   agency [0]\n# ... with 3 variables: agency <dbl>, agency_name <chr>, Receipts <dbl>\n```\n:::\n\n```{.r .cell-code}\nfunds_past <- allrevfiles22  %>% filter(fy < 2022) %>% mutate(fund == as.character(fund)) %>% group_by(fund, fund_name) %>% summarize(count = n(), Receipts = sum(receipts, na.rm = TRUE))  %>% drop_na()\n\nfunds22 <- allrevfiles22  %>% filter(fy == 2022) %>% mutate(fund == as.character(fund)) %>% group_by(fund, fund_name) %>%  summarize(count = n(), Receipts = sum(receipts, na.rm = TRUE)) %>% unique() %>% drop_na()\n\n# 19 revenue funds were in FY22 revenue data that were not in past data \n\n# some could be small fund name changes\n\nanti_join(funds22, funds_past, by = c(\"fund\", \"fund_name\")) %>% arrange(fund)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 19 x 4\n# Groups:   fund [19]\n   fund  fund_name                      count    Receipts\n   <chr> <chr>                          <int>       <dbl>\n 1 0165  RONALD MCDONALD HOUSE CHARITY      1     143893.\n 2 0319  PENSION STABILIZATION              1  300000000 \n 3 0351  FREEDOM SCHOOLS                    1   17000000 \n 4 0367  CAP FACILITY TEC MODERNIZATION     1    5300000 \n 5 0392  EQUAL PAY REGISTRATION             1      24150 \n 6 0422  ELECTRIC VEHICLE REBATE            3   13528800 \n 7 0427  ENERGY TRANSITION ASSISTANCE       1   28773075.\n 8 0544  DOIT SPECIAL PROJECTS              2    9998632.\n 9 0628  ESSENTIAL GOVT SERV SUPPORT        1 1000000000 \n10 0634  STATE TREASURER'S CAPITAL          2     273192.\n11 0656  HORSE RACING PURSE EQUITY          1    5908048.\n12 0672  CONSUMER INTERVENOR COMP.          1    1220000 \n13 0683  GROCERY TAX REPLACEMENT            1  325000000 \n14 0723  REVOCATION ENFORCEMENT             1     749073.\n15 0742  ST. POLICE TRAINING & ACADEMY      1    2803359.\n16 0743  LAW ENFORCEMENT TRAINING           1   25230230.\n17 0848  SETTLEMENT                         1    5000000 \n18 0966  ILLINOIS WORKS                     1   10000000 \n19 0976  FAIRGROUNDS IMPROVMNT & RACING     3      93664.\n```\n:::\n\n```{.r .cell-code}\nsources_past <- allrevfiles22  %>% filter(fy < 2022) %>% mutate(source == as.character(source)) %>% group_by(source, source_name) %>% summarize(count = n(), Receipts = sum(receipts, na.rm = TRUE))  %>% drop_na()\n\nsources22 <- allrevfiles22  %>% filter(fy == 2022) %>% mutate(source == as.character(source)) %>% group_by(source, source_name) %>%  summarize(count = n(), Receipts = sum(receipts, na.rm = TRUE)) %>% unique()\n\n# 20 revenue sources were in FY22 data that were not in past data \n\n# some could be small source name changes:\n\nanti_join(sources22, sources_past, by = c(\"source\", \"source_name\")) %>% arrange(source)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 20 x 4\n# Groups:   source [20]\n   source source_name                    count   Receipts\n   <chr>  <chr>                          <int>      <dbl>\n 1 0303   LOTTERY-ILOTTERY SETTLEMENT        1 177417302.\n 2 2292   VIDEO TERMINAL TAX                 3 893824162.\n 3 2457   E ST LOUIS FINANCE AUTH            1     41667.\n 4 2590   ALTON CENTER BUSINESS PARK         1    291667.\n 5 2611   E-PAY ADMINISTRATION FEES          1   1136121.\n 6 2660   CONCESSION REVENUE-FOOD            1     17210.\n 7 2682   SW BADGE REPLACEMENT FEES          1        10 \n 8 2699   RB RECONCILIATION FEE              1  15000000 \n 9 2729   NORTH PARK COLLEGE LIC PLATES      1        20 \n10 2736   STATE ST INSTITNL US GOV FND       1   1622448.\n11 2737   VGA - IL STATE FAIR OP FEES        1     48387.\n12 2738   VGA-DU QUOIN STATE FAIR OP FEE     1     11029.\n13 2739   PUBLIC UTILITIES                   1   1220000 \n14 2740   ENRGY TRANSITION ASST/ELECTRIC     1  28773075.\n15 2742   OPERATION ASSESSMENT FEE           1   2828085.\n16 2745   FY22 TITLE INCREASE                1   3072054 \n17 2747   BUSINESS FILING FEE                1     24150 \n18 2748   CORN COMMODITY SPONSORS            1      5000 \n19 2755   PUBLIC UTIL - ETHICS REPRT FEE     1   1235000 \n20 2756   UNEXP CAPITAL IMP PROJECTS         1     90583.\n```\n:::\n:::\n\n\nSources 2737 through 2756 were not found in the IOC_source file so I added them to \\`ioc_source_updated22_AWM.xlsx\\`. They do NOT have a rev_type until the Fiscal Futures researchers discuss which revenue type the sources fall under and if they should be included in the analysis in general.\n\n### Recoding New and Reused Funds\n\nNew funds will need to be manually added to the funds_ab_in excel file and determined if they should or should not be included in Fiscal Future calculations.\n\nFor funds that were reused once, a 9 replaces the 0 as the first digit. If reused twice, then the first two values are 10.\n\n\\- Ex. 0350 \\--\\> 9350 because its use changed.\n\n\\- Ex. 0367 becomes 10367 because its use has changed twice now. There was fund 0367 originally, then its use changed and it was recoded as 9367, and now it changed again so it is a 10367.\n\n\\- Excel file also has alternative ways to name funds (e.g. 0397-A and 0397-B) and variables for the year that the fund stopped being used. These have not been updated consistently over the years but it is useful information when trying to find any coding mistakes from the past.\n\nNew or reused funds revenue file recoding:\n\n\n::: {.cell hash='index_cache/html/recode-rev-funds_7d3e0cf53d0a67e0576ef2cba6f9c745'}\n\n```{.r .cell-code}\n# if first character is a 0, replace with a 9 if its purpose has changed\n\nrev_1998_2022 <- allrevfiles22 %>%\n\n      mutate(fund = ifelse(fy < 2002 & fund %in% c(\"0730\", \"0241\", \"0350\", \"0367\", \"0381\", \"0382\", \"0526\", \"0603\", \"0734\", \"0913\", \"0379\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund = ifelse (fy < 2008 & fund %in% c(\"0027\", \"0033\", \"0037\", \"0058\", \"0062\", \"0066\", \"0075\", \"0083\", \"0116\", \"0119\", \"0120\", \"0122\", \"0148\", \"0149\", \"0157\", \"0158\", \"0166\", \"0194\", \"0201\", \"0209\", \"0211\", \"0217\", \"0223\", \"0231\", \"0234\", \"0253\", \"0320\", \"0503\", \"0505\", \"0512\", \"0516\", \"0531\", \"0532\", \"0533\", \"0547\", \"0563\", \"0579\", \"0591\", \"0606\", \"0616\", \"0624\", \"0659\", \"0662\", \"0665\", \"0676\", \"0710\", \n\n\"0068\", \"0076\", \"0115\", \"0119\", \"0168\", \"0182\", \"0199\", \"0241\", \"0307\", \"0506\", \"0509\", \"0513\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund = ifelse(fy < 2016 & fund %in% c(\"0263\", \"0399\", \"0409\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund =  ifelse(fy < 2017 & fund == \"0364\", str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund =  ifelse(fy < 2018 & fund %in% c(\"0818\", \"0767\", \"0671\", \"0593\", \"0578\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund = ifelse(fy>1999 & fy < 2018 & fund == \"0231\", \"10231\", fund) ) %>%\n\n  \n\n  mutate(fund = ifelse(fy < 2019 & fund %in% c(\"0161\", \"0489\", \"0500\", \"0612\", \"0893\", \"0766\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund =  ifelse(fy < 2020 & fund %in% c(\"0254\", \"0304\", \"0324\", \"0610\", \"0887\", \"0908\", \"0939\", \"0968\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund =  ifelse(fy < 2021 & fund %in% c(\"0255\", \"0325\", \"0348\", \"0967\", \"0972\"), str_replace(fund, \"0\",\"9\"), fund) ) %>%\n\n  \n\n   #2022 changes\n\n  mutate(fund = ifelse(fy < 2022 & fund %in% c(\"0110\",\"0165\",\"0351\", \"0392\", \"0393\", \"0422\", \"0544\", \"0628\", \"0634\",  \"0656\", \"0672\", \"0683\", \"0723\", \"0742\", \"0743\"), str_replace(fund, \"0\",\"9\"), as.character(fund))) %>%  # replaces first 0 it finds with a 9\n\n  mutate(fund = ifelse(fy < 2022 & fund == \"0367\", \"10367\", as.character(fund)) # fund reused for 3rd time\n\n)\n```\n:::\n\n\nFor 2022, new funds included The Essential Government Services fund, Electric Vehicle Rebate, Budget Stabilization fund, and more. New funds were added to the funds_ab_in.xlsx file and recoded funds were addressed in the code chunks below and updated in the same excel file.\n\nExpenditure recoding:\n\n\n::: {.cell hash='index_cache/html/recode-exp-funds_d80cb6d6858e0849084feb774b751a87'}\n\n```{.r .cell-code}\n# if first character is a 0, replace with a 9\n\nexp_1998_2022 <- allexpfiles22 %>%\n\n      mutate(fund = ifelse(fy < 2002 & fund %in% c(\"0730\", \"0241\", \"0350\", \"0367\", \"0381\", \"0382\", \"0526\", \"0603\", \"0734\", \"0913\", \"0379\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund = ifelse(fy < 2008 & fund %in% c(\"0027\", \"0033\", \"0037\", \"0058\", \"0062\", \"0066\", \"0075\", \"0083\", \"0116\", \"0119\", \"0120\", \"0122\", \"0148\", \"0149\", \"0157\", \"0158\", \"0166\", \"0194\", \"0201\", \"0209\", \"0211\", \"0217\", \"0223\", \"0231\", \"0234\", \"0253\", \"0320\", \"0503\", \"0505\", \"0512\", \"0516\", \"0531\", \"0532\", \"0533\", \"0547\", \"0563\", \"0579\", \"0591\", \"0606\", \"0616\", \"0624\", \"0659\", \"0662\", \"0665\", \"0676\", \"0710\", \n\n\"0068\", \"0076\", \"0115\", \"0119\", \"0168\", \"0182\", \"0199\", \"0241\", \"0307\", \"0506\", \"0509\", \"0513\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund = ifelse(fy < 2016 & fund %in% c(\"0263\", \"0399\", \"0409\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund =  ifelse(fy < 2017 & fund == \"0364\", str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund =  ifelse(fy < 2018 & fund %in% c(\"0818\", \"0767\", \"0671\", \"0593\", \"0578\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  mutate(fund = ifelse(fy>1999 & fy < 2018 & fund == \"0231\", \"10231\", fund) ) %>%\n\n  \n\n  mutate(fund = ifelse(fy < 2019 & fund %in% c(\"0161\", \"0489\", \"0500\", \"0612\", \"0893\", \"0766\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund =  ifelse(fy < 2020 & fund %in% c(\"0254\", \"0304\", \"0324\", \"0610\", \"0887\", \"0908\", \"0939\", \"0968\"), str_replace(fund, \"0\",\"9\"), fund)) %>%\n\n  \n\n  mutate(fund =  ifelse(fy < 2021 & fund %in% c(\"0255\", \"0325\", \"0348\", \"0967\", \"0972\"), str_replace(fund, \"0\",\"9\"), fund))  %>%\n\n  \n\n  #2022 changes\n\n  mutate(fund = ifelse(fy < 2022 & fund %in% c(\"0110\",\"0165\",\"0351\", \"0392\", \"0393\", \"0422\", \"0544\", \"0628\", \"0634\",  \"0656\", \"0672\", \"0683\",\"0723\", \"0742\", \"0743\"), str_replace(fund, \"0\",\"9\"), as.character(fund))) %>%  # replaces first 0 it finds with a 9\n\n  mutate(fund = ifelse(fy < 2022 & fund == \"0367\", \"10367\", as.character(fund)) # fund reused for 3rd time \n\n  )\n```\n:::\n\n\nThe \\`funds_ab_in.xlsx\\` file contains all funds that have existed since 1998, if they still exist, indicates if fund numbers have been reused for varying purposes, and is updated yearly with new fund numbers used by the IOC.\n\n\n::: {.cell hash='index_cache/html/create-exp_temp_9c67a152f319d89e203b86a644b3c429'}\n\n```{.r .cell-code}\nfunds_ab_in_2022 = readxl::read_excel(\"C:/Users/aleaw/OneDrive/Documents/PhD Fall 2021 - Spring 2022/Merriman RA/Fiscal Futures FY2022/Replication-Files/funds_ab_in_2022.xlsx\")\n\nexp_temp <- exp_1998_2022 %>% \n\n  arrange(fund, fy) %>%\n\n  filter(expenditure != 0) %>%             # keeps everything that is not zero\n\n# join  funds_ab_in_2021  to exp_temp\n\n left_join(funds_ab_in_2022, by = \"fund\")  # matches most recent fund number \n\n# Agency == 799 for Statutory transfers \n\n#  Object == 1993 is for Interfund cash transfers  \n\nexp_temp <- exp_temp %>% \n\n  mutate(transfer = ifelse(org_name == \"TRANSFERS\", 1, 0),\n\n         trans_agency = ifelse(org_name == \"TRANSFERS\", str_sub(obj_seq_type,1,3), trans_agency),\n\n         trans_type = ifelse(org_name == \"TRANSFERS\", str_sub(obj_seq_type,4,9), trans_type)\n\n         )\n```\n:::\n\n\n\\- the initial combined years of data are saved as dataframes named \\`exp_1998_2022\\` and \\`rev_1998_2022\\`. These are then saved as exp_temp and rev_temp while recoding variables. This is BEFORE category groups are created and cleaned below. \\`exp_temp\\` and \\`rev_temp\\` are only temporary files; do not use for aggregating totals yet!\n\n\n\n\n\nUpdate Agencies: Some agencies have merged with others or changed names over time.\n\n\n::: {.cell hash='index_cache/html/agencies-exp_78bd2b264f6b20a8481ae62645a8caaa'}\n\n```{.r .cell-code}\n# recodes old agency numbers to consistent agency number\n\nexp_temp <- exp_temp %>% \n\n  mutate(agency = case_when(\n\n    (agency==\"438\"| agency==\"475\" |agency == \"505\") ~ \"440\",\n\n    # financial institution &  professional regulation &\n\n     # banks and real estate  --> coded as  financial and professional reg\n\n    agency == \"473\" ~ \"588\", # nuclear safety moved into IEMA\n\n    (agency ==\"531\" | agency ==\"577\") ~ \"532\", # coded as EPA\n\n    (agency ==\"556\" | agency == \"538\") ~ \"406\", # coded as agriculture\n\n    agency == \"560\" ~ \"592\", # IL finance authority (fire trucks and agriculture stuff)to state fire marshal\n\n    agency == \"570\" & fund == \"0011\" ~ \"494\",   # city of Chicago road fund to transportation\n\n    TRUE ~ (as.character(agency)))) \n```\n:::\n\n\nFor aggregating revenue, use the rev_1998_2022 dataframe, join the funds_ab_in_2022 file to it, and then join the ioc_source_type file to the dataset. Remember: You need to update the funds_ab_in and ioc_source_type file every year!\n\n\n::: {.cell hash='index_cache/html/unnamed-chunk-5_3627c2d9c65c800fdd7c4d3dac8942f3'}\n\n```{.r .cell-code}\n# fund info to revenue for all years\n\nrev_temp <- inner_join(rev_1998_2022, funds_ab_in_2022, by = \"fund\") %>% arrange(source)\n\n# need to update the ioc_source_type file every year! \n\nioc_source_type <- readxl::read_xlsx(\"C:/Users/aleaw/OneDrive/Documents/PhD Fall 2021 - Spring 2022/Merriman RA/Fiscal Futures FY2022/Replication-Files/ioc_source_updated22_AWM.xlsx\")\n\nrev_temp <- left_join(rev_temp, ioc_source_type, by = \"source\")\n\n# automatically used source, source name does not match for the join to work using source_name\n\n# recodes old agency numbers to consistent agency number\n\nrev_temp <- rev_temp %>% \n\n  mutate(agency = case_when(\n\n    (agency==\"438\"| agency==\"475\" |agency == \"505\") ~ \"440\",\n\n    # financial institution &  professional regulation &\n\n     # banks and real estate  --> coded as  financial and professional reg\n\n    agency == \"473\" ~ \"588\", # nuclear safety moved into IEMA\n\n    (agency ==\"531\" | agency ==\"577\") ~ \"532\", # coded as EPA\n\n    (agency ==\"556\" | agency == \"538\") ~ \"406\", # coded as agriculture\n\n    agency == \"560\" ~ \"592\", # IL finance authority (fire trucks and agriculture stuff)to state fire marshal\n\n    agency == \"570\" & fund == \"0011\" ~ \"494\",   # city of Chicago road fund to transportation\n\n    TRUE ~ (as.character(agency))))\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}